### PR TITLE
updated jade logo

### PR DESCRIPTION
**Pull request by GarthDB**
Jade has a [new logo](https://github.com/jadejs/jade/issues/1882); here's an update.

### CODE REVIEW

**Comment by kennethormandy** [comment]
Thanks @GarthDB! If you want to open a PR [here](https://github.com/chloi/preprocessor-logos), that will probably get turned into the parent library. If not, that’s cool too, I can port it.

**Comment by GarthDB** [comment]
@kennethormandy I can do that - do you need me to do that before this pull request can be accepted?

**Comment by GarthDB** [comment]
I can break this into another pull request if you'd prefer, but the site's [pagespeed score is pretty low](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fharpjs.com%2F&tab=desktop). Every little bit of performance counts, especially for a project like this.

I've started by optimizing the svgs and a couple of the pngs. To be honest, I think most (if not all) of the svgs would be smaller as svgs as well. I could recreate them, but if anyone has the original vector files it would be faster to use the original source.

After the images it would be good to consider using CloudFlare's free [optimizations](https://www.cloudflare.com/features-optimizer) to minimize and gzip the content.

**Comment by kennethormandy** [comment]
Thanks for this! Sorry I took so long to merge it.

I do have the original `.png`s as `.svg`s, but I believe I checked them and their complexity meant inlining them wasn’t actually as efficient as making them `.png`s. But maybe keeping them in image tags and referencing them would still be better.

The site is published on [Surge.sh](https://surge.sh) which we make, everything else is minified and gzipped automatically, but we aren’t doing that with SVG the image sometimes. We also use an ETag-based to caching headers that Google’s Page Speed doesn’t really take into consideration, so that might be the cause of some of the lower numbers. We have an 84% on Pingdom which seems alright, and good results for everything that is in our control [on WebPagetest](http://www.webpagetest.org/result/150831_0G_14FF/1/performance_optimization/) (ex. we can’t cache Google Analytics, Twitter widgets, etc. of course).

I really appreciate that you took the time to take a look at that and make the SVG improvements however, and am totally open to more suggestions if you have ‘em. Thanks @GarthDB!

**Pull request merged**
